/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ControlDAO.Coneccao;
import ControlDAO.ControleInspecao;
import Model.ModeloInspecao;

/**
 *
 * @author trindade
 */
public class FormularioInspecao extends javax.swing.JFrame {

        ModeloInspecao mod = new ModeloInspecao();
        ControleInspecao control = new ControleInspecao();
        Coneccao conex = new Coneccao();
    /**
     * Creates new form FormularioInspecao
     */
    public FormularioInspecao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbCondicoesFiacao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfOrdemServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDataInspecao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEtiquetaPoste = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbSalvarCadastroInspeção = new javax.swing.JButton();
        jbNovoCadastroInspeção = new javax.swing.JButton();
        jbCancelarCadastroInspeção = new javax.swing.JButton();
        jbExcluirCadastroInspeção = new javax.swing.JButton();
        jbPesquisarInspecao = new javax.swing.JButton();
        jtfPesquisarInspecao = new javax.swing.JTextField();
        jcbPrumo = new javax.swing.JComboBox<>();
        jcbEstadoPoste = new javax.swing.JComboBox<>();
        jcbCondicaoFiacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("Cadastro de Inspeção");

        jcbCondicoesFiacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Ordem de Serviço:");

        jtfOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOrdemServicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        jtfDataInspecao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setText("Etiqueta do Poste:");

        jLabel5.setText("Estado do Poste:");

        jLabel6.setText("Prumo:");

        jLabel7.setText("Condições da fiação");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbSalvarCadastroInspeção.setText("Salvar");
        jbSalvarCadastroInspeção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCadastroInspeçãoActionPerformed(evt);
            }
        });

        jbNovoCadastroInspeção.setText("Novo");
        jbNovoCadastroInspeção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoCadastroInspeçãoActionPerformed(evt);
            }
        });

        jbCancelarCadastroInspeção.setText("Cancelar");
        jbCancelarCadastroInspeção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarCadastroInspeçãoActionPerformed(evt);
            }
        });

        jbExcluirCadastroInspeção.setText("Excluir");

        jbPesquisarInspecao.setText("Pesquisar");

        jtfPesquisarInspecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarInspecaoActionPerformed(evt);
            }
        });

        jcbPrumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jcbEstadoPoste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bom", "Ruim" }));
        jcbEstadoPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoPosteActionPerformed(evt);
            }
        });

        jcbCondicaoFiacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boa", "Ruim" }));
        jcbCondicaoFiacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCondicaoFiacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcbCondicoesFiacaoLayout = new javax.swing.GroupLayout(jcbCondicoesFiacao);
        jcbCondicoesFiacao.setLayout(jcbCondicoesFiacaoLayout);
        jcbCondicoesFiacaoLayout.setHorizontalGroup(
            jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                        .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfEtiquetaPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDataInspecao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbEstadoPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPrumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCondicaoFiacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcbCondicoesFiacaoLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jtfPesquisarInspecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisarInspecao)))
                .addContainerGap())
            .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jbSalvarCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovoCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelarCadastroInspeção)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluirCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jcbCondicoesFiacaoLayout.setVerticalGroup(
            jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcbCondicoesFiacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfOrdemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDataInspecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfEtiquetaPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbEstadoPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jcbPrumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCondicaoFiacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisarInspecao)
                    .addComponent(jtfPesquisarInspecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jcbCondicoesFiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovoCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelarCadastroInspeção)
                    .addComponent(jbExcluirCadastroInspeção))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcbCondicoesFiacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcbCondicoesFiacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOrdemServicoActionPerformed

    
    
    private void jbSalvarCadastroInspeçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCadastroInspeçãoActionPerformed
        mod.setOs(Integer.parseInt(jtfOrdemServico.getText()));
        mod.setDate((String) jtfDataInspecao.getText());
        mod.setEstado((String) jcbEstadoPoste.getSelectedItem()); 
        mod.setPrumo((String) jcbPrumo.getSelectedItem()); ////verificar se erro
        mod.setFiacao((String) jcbCondicaoFiacao.getSelectedItem());
        mod.setEtiquetaPoste(Integer.parseInt(jtfEtiquetaPoste.getText()));
                
        control.Salvar(mod);        
        
        jtfDataInspecao.setText("");
        jtfEtiquetaPoste.setText("");
        jtfOrdemServico.setText("");
        jtfOrdemServico.setText("");
    }//GEN-LAST:event_jbSalvarCadastroInspeçãoActionPerformed

    private void jbNovoCadastroInspeçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoCadastroInspeçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNovoCadastroInspeçãoActionPerformed

    private void jbCancelarCadastroInspeçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarCadastroInspeçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarCadastroInspeçãoActionPerformed

    private void jtfPesquisarInspecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarInspecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarInspecaoActionPerformed

    private void jcbEstadoPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoPosteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoPosteActionPerformed

    private void jcbCondicaoFiacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCondicaoFiacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCondicaoFiacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioInspecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioInspecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancelarCadastroInspeção;
    private javax.swing.JButton jbExcluirCadastroInspeção;
    private javax.swing.JButton jbNovoCadastroInspeção;
    private javax.swing.JButton jbPesquisarInspecao;
    private javax.swing.JButton jbSalvarCadastroInspeção;
    private javax.swing.JComboBox<String> jcbCondicaoFiacao;
    private javax.swing.JPanel jcbCondicoesFiacao;
    private javax.swing.JComboBox<String> jcbEstadoPoste;
    private javax.swing.JComboBox<String> jcbPrumo;
    private javax.swing.JTextField jtfDataInspecao;
    private javax.swing.JTextField jtfEtiquetaPoste;
    private javax.swing.JTextField jtfOrdemServico;
    private javax.swing.JTextField jtfPesquisarInspecao;
    // End of variables declaration//GEN-END:variables
}
