/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ControlDAO.Coneccao;
import static java.sql.DriverManager.println;
import static javafx.application.Application.launch;
import javax.swing.JOptionPane;

/**
 *
 * @author trindade
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Coneccao conecta = new Coneccao();

    public TelaPrincipal() {
        initComponents();
            conecta.coneccao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jifCadastro = new javax.swing.JInternalFrame();
        jpCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadatroPoste = new javax.swing.JButton();
        jButtonCadastroCaixa = new javax.swing.JButton();
        jButtonCadastroInspeção = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbFechaCadastro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmMenuCadastroPoste = new javax.swing.JMenuItem();
        jmMenuCadastroCaixa = new javax.swing.JMenuItem();
        jmMenuiCadastroInspecao = new javax.swing.JMenuItem();
        jmMenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmFerramenta = new javax.swing.JMenu();
        jmTelaCadastro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jifCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jifCadastro.setTitle("Cadastro");
        jifCadastro.setVisible(true);
        jifCadastro.getContentPane().setLayout(null);

        jpCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Cadastros");

        jButtonCadatroPoste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PosteTeste.png"))); // NOI18N
        jButtonCadatroPoste.setToolTipText("Cadastro de Poste");
        jButtonCadatroPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadatroPosteActionPerformed(evt);
            }
        });

        jButtonCadastroCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EnergyBoxColor.png"))); // NOI18N
        jButtonCadastroCaixa.setToolTipText("Cadastro de Caixa");
        jButtonCadastroCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCaixaActionPerformed(evt);
            }
        });

        jButtonCadastroInspeção.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Inspec_1.png"))); // NOI18N
        jButtonCadastroInspeção.setToolTipText("Cadastrar Inspeção");
        jButtonCadastroInspeção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroInspeçãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroLayout = new javax.swing.GroupLayout(jpCadastro);
        jpCadastro.setLayout(jpCadastroLayout);
        jpCadastroLayout.setHorizontalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jpCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonCadatroPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastroCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jpCadastroLayout.setVerticalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastroInspeção, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonCadatroPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 97, Short.MAX_VALUE))
        );

        jifCadastro.getContentPane().add(jpCadastro);
        jpCadastro.setBounds(10, 40, 630, 200);

        jLabel2.setFont(new java.awt.Font("Manjari Bold", 1, 12)); // NOI18N
        jLabel2.setText("Magnani Inspect");
        jifCadastro.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 220, 30);

        jbFechaCadastro.setText("Fechar");
        jbFechaCadastro.setToolTipText("Fecha tela Cadastro");
        jbFechaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaCadastroActionPerformed(evt);
            }
        });
        jifCadastro.getContentPane().add(jbFechaCadastro);
        jbFechaCadastro.setBounds(550, 10, 80, 31);

        getContentPane().add(jifCadastro);
        jifCadastro.setBounds(0, 30, 650, 270);

        jmCadastro.setText("Cadastro");

        jmMenuCadastroPoste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmMenuCadastroPoste.setText("Poste");
        jmMenuCadastroPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuCadastroPosteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmMenuCadastroPoste);

        jmMenuCadastroCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmMenuCadastroCaixa.setText("Caixa de Inspeção");
        jmMenuCadastroCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuCadastroCaixaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmMenuCadastroCaixa);

        jmMenuiCadastroInspecao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jmMenuiCadastroInspecao.setText("Inspeção");
        jmMenuiCadastroInspecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuiCadastroInspecaoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmMenuiCadastroInspecao);

        jmMenuSair.setText("Sair");
        jmMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMenuSairActionPerformed(evt);
            }
        });
        jmCadastro.add(jmMenuSair);

        jMenuBar1.add(jmCadastro);

        jMenu2.setText("Relatório");
        jMenuBar1.add(jMenu2);

        jmFerramenta.setText("Ferramenta");

        jmTelaCadastro.setText("Tela Cadastro");
        jmTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaCadastroActionPerformed(evt);
            }
        });
        jmFerramenta.add(jmTelaCadastro);

        jMenuBar1.add(jmFerramenta);

        jMenu1.setText("jMenu1");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(664, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuCadastroPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuCadastroPosteActionPerformed
        // Chama a tela de Cadastro de Poste pelo menu
        FormularioPoste tela = new FormularioPoste();
        tela.setVisible(true);
    }//GEN-LAST:event_jmMenuCadastroPosteActionPerformed

    private void jmMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuSairActionPerformed
        // Exibe perguta de confirmação de encerramento de programa
        JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Sair");
        conecta.desconecta();
        System.exit(0);
     
    }//GEN-LAST:event_jmMenuSairActionPerformed

    private void jmMenuCadastroCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuCadastroCaixaActionPerformed
        // Chama tela de cadastro de inspeção de poste via menu
        FormularioInspecao telaInspecao = new FormularioInspecao();
        telaInspecao.setVisible(true);
        
    }//GEN-LAST:event_jmMenuCadastroCaixaActionPerformed

    private void jButtonCadatroPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadatroPosteActionPerformed
        // Chama tela de cadastro de poste via botão personalizado na tela inicial
        FormularioPoste telaCadastroPoste = new FormularioPoste();
        telaCadastroPoste.setVisible(true);
    }//GEN-LAST:event_jButtonCadatroPosteActionPerformed

    private void jbFechaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaCadastroActionPerformed
            // Fecha tela do Cadastro
        jifCadastro.dispose();
    }//GEN-LAST:event_jbFechaCadastroActionPerformed

    private void jmMenuiCadastroInspecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMenuiCadastroInspecaoActionPerformed
        // Chama tela de cadastro via menu
        FormularioInspecao telaInspecao = new FormularioInspecao();
        telaInspecao.setVisible(true);
    }//GEN-LAST:event_jmMenuiCadastroInspecaoActionPerformed

    private void jmTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaCadastroActionPerformed
        // Chama Tela de Cadastro dos Postes
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmTelaCadastroActionPerformed

    private void jButtonCadastroCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCaixaActionPerformed
        // ja sabe que se faz esse função
        FormularioCaixa telaCadastroCaixa = new FormularioCaixa();
        telaCadastroCaixa.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroCaixaActionPerformed

    private void jButtonCadastroInspeçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroInspeçãoActionPerformed
        
        FormularioInspecao telaInspecao = new FormularioInspecao();
        telaInspecao.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroInspeçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCaixa;
    private javax.swing.JButton jButtonCadastroInspeção;
    private javax.swing.JButton jButtonCadatroPoste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbFechaCadastro;
    private javax.swing.JInternalFrame jifCadastro;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmFerramenta;
    private javax.swing.JMenuItem jmMenuCadastroCaixa;
    private javax.swing.JMenuItem jmMenuCadastroPoste;
    private javax.swing.JMenuItem jmMenuSair;
    private javax.swing.JMenuItem jmMenuiCadastroInspecao;
    private javax.swing.JMenuItem jmTelaCadastro;
    private javax.swing.JPanel jpCadastro;
    // End of variables declaration//GEN-END:variables
}
