/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;

/**
 *
 * @author trindade
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jifCadastro = new javax.swing.JInternalFrame();
        jpCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbFechaCadastro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmPoste = new javax.swing.JMenuItem();
        jmCaixa = new javax.swing.JMenuItem();
        jmInspecao = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmFerramenta = new javax.swing.JMenu();
        jmTelaCadastro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jifCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jifCadastro.setTitle("Cadastro");
        jifCadastro.setVisible(true);
        jifCadastro.getContentPane().setLayout(null);

        jpCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Cadastros");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PosteTeste.png"))); // NOI18N
        jButton1.setToolTipText("Cadastro de Poste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EnergyBoxColor.png"))); // NOI18N
        jButton2.setToolTipText("Cadastro de Caixa");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Inspec_1.png"))); // NOI18N
        jButton3.setToolTipText("Cadastrar Inspeção");

        javax.swing.GroupLayout jpCadastroLayout = new javax.swing.GroupLayout(jpCadastro);
        jpCadastro.setLayout(jpCadastroLayout);
        jpCadastroLayout.setHorizontalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jpCadastroLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jpCadastroLayout.setVerticalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 97, Short.MAX_VALUE))
        );

        jifCadastro.getContentPane().add(jpCadastro);
        jpCadastro.setBounds(10, 40, 630, 200);

        jLabel2.setFont(new java.awt.Font("Manjari Bold", 1, 12)); // NOI18N
        jLabel2.setText("Magnani Inspect");
        jifCadastro.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 220, 30);

        jbFechaCadastro.setText("Fechar");
        jbFechaCadastro.setToolTipText("Fecha tela Cadastro");
        jbFechaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaCadastroActionPerformed(evt);
            }
        });
        jifCadastro.getContentPane().add(jbFechaCadastro);
        jbFechaCadastro.setBounds(550, 10, 80, 31);

        getContentPane().add(jifCadastro);
        jifCadastro.setBounds(0, 30, 650, 270);

        jmCadastro.setText("Cadastro");

        jmPoste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmPoste.setText("Poste");
        jmPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPosteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmPoste);

        jmCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmCaixa.setText("Caixa de Inspeção");
        jmCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCaixaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCaixa);

        jmInspecao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jmInspecao.setText("Inspeção");
        jmInspecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInspecaoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmInspecao);

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmCadastro.add(jmSair);

        jMenuBar1.add(jmCadastro);

        jMenu2.setText("Relatório");
        jMenuBar1.add(jMenu2);

        jmFerramenta.setText("Ferramenta");

        jmTelaCadastro.setText("Tela Cadastro");
        jmTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTelaCadastroActionPerformed(evt);
            }
        });
        jmFerramenta.add(jmTelaCadastro);

        jMenuBar1.add(jmFerramenta);

        jMenu1.setText("jMenu1");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(664, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPosteActionPerformed
        // TODO add your handling code here:
        FormularioPoste tela = new FormularioPoste();
        tela.setVisible(true);
    }//GEN-LAST:event_jmPosteActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Sair");
        System.exit(0);
        
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCaixaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormularioPoste tela = new FormularioPoste();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbFechaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaCadastroActionPerformed
    
        // Fecha tela do Cadastro
        jifCadastro.dispose();
    }//GEN-LAST:event_jbFechaCadastroActionPerformed

    private void jmInspecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInspecaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmInspecaoActionPerformed

    private void jmTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTelaCadastroActionPerformed
        // Chama Tela de Cadastro dos Postes
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmTelaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbFechaCadastro;
    private javax.swing.JInternalFrame jifCadastro;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCaixa;
    private javax.swing.JMenu jmFerramenta;
    private javax.swing.JMenuItem jmInspecao;
    private javax.swing.JMenuItem jmPoste;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenuItem jmTelaCadastro;
    private javax.swing.JPanel jpCadastro;
    // End of variables declaration//GEN-END:variables
}
